# Basic Information 
title: Hanyang Chen
subtitle: （陈晗阳）
position: Incoming Ph.D. Student
# affiliation: Arizona State University
# affiliation_link: https://www.asu.edu/
email: hanyang-chen [at] outlook.com

# Search Engine Optimization (SEO)
keywords: hanyang chen, chen hanyang, hanyangchen, chenhanyang, 陈晗阳
canonical: https://hanyang-chen.github.io/
description: Hanyang Chen is an incoming Ph.D. student at the Arizona State University. His research lies in reinforcement learning, data mining, and large language models.

# The option is used to show the last update time.
enable_last_update: true

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=_xGaoJ8AAAAJ
github_link: https://hanyang-chen.github.io/
cv_link: /assets/files/cv.pdf
github_link: https://github.com/hanyang-chen
linkedin: https://www.linkedin.com/in/hanyang-chen-lokol/
# twitter: https://twitter.com/YaoyaoLiu1/

# Images 
avatar: /assets/img/life.jpg

# Footnotes
footnote: Powered by Jekyll and Minimal Light theme.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project.
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: uMIO01ueSitrFq3z7QUTj1z2cxswlDeOfXg5pKXwxbs

# Google Analytics 4 (gtag.js)
google_analytics_id: G-HGY04MME0D

permalink: /blogs/:title/

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - html_source_file
