reviewers:
  - name: "ACM SIGKDD Conference on Knowledge Discovery and Data Mining (KDD)"
    url: "https://kdd2026.kdd.org/"
    year: "2026"

  - name: "Winter Conference on Applications of Computer Vision (WACV)"
    url: "https://wacv.thecvf.com/"
    year: "2026-2027"

  - name: "Annual Conference on Neural Information Processing Systems (NeurIPS)"
    url: "https://nips.cc/Conferences/2026/"
    year: "2025-2026"

  - name: "China Conference on Knowledge Graph and Semantic Computing (CCKS)"
    url: "https://sigkg.cn/ccks2025/"
    year: "2025"

teaching:
  - course: "C402002B, Deep Learning"
    semesters: "Fall 2024 & Fall 2025"
